version: '3'

services:
  api:
    image: douqin/node-server-app-chat-chit:latest
    container_name: chat-chit-node-api
    environment:
      - DATABASE_PORT=3306
      - DATABASE_NAME=dxlampr1_dbappchat
      - DATABASE_USER=root
      - DATABASE_PASSWORD=a
      - DATABASE_HOST=mysql-server
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    ports:
      - '3000:3000'
    depends_on:
      - mysql-server
      - redis

  mysql-server:
    image: mysql:8
    container_name: mysql-v8-container
    restart: always
    environment:
      - MYSQL_DATABASE=dxlampr1_dbappchat
      - MYSQL_ROOT_PASSWORD=a
    ports:
      - '3306:3306'
    expose:
      - 3306
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin:5
    container_name: phpmyadmin-container
    restart: always
    ports:
      - '8088:80'
    environment:
      - PMA_HOST=mysql-server
  redis:
    image: redis:7.0-alpine
    restart: always
    ports:
      - '6379:6379'
    container_name: redis-cache
