name: Docker Image CI

on:
  push:
    branches: ["feature-action-for-build-container"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: move context build
        run: cd server-app-chat-chit
      - name: check context
        run: ls
      # - name: build image
      #   run: docker build -t douqin/server-app-chat-chit:latest -f server-app-chat-chit/Dockerfile server-app-chat-chit
      - name: log secrect
        run: echo ${{secrets.DOCKER_USERNAME}}
      - name: login docker
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      # - name: tag image
      #   run: docker tag douqin/server-app-chat-chit:latest douqin/server-app-chat-chit:latest
      # - name: push image
      #   run: docker push douqin/server-app-chat-chit:latest
